server:
  port: 9999


spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9b309.p.ssafy.io:3306/howdoilook?serverTimezone=Asia/Seoul
    username: i9B309
    password: ***REMOVED***

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update



  # mongoDB
#  data:
#    mongodb:
#    #uri: mongodb+srv://S09P13B304:ssafy@ssafy.ngivl.mongodb.net/S09P13B304?authSource=admin
