server:
  port: 8082

spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PUBLIC_IP}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update



  # mongoDB
#  data:
#    mongodb:
#    #uri: mongodb+srv://S09P13B304:ssafy@ssafy.ngivl.mongodb.net/S09P13B304?authSource=admin
